### ISSUE TITLE
May I ask why choose 15 as the max depth? Is this parameter important to depth map visualization?

### ISSUE THREAD

**Issue by gwxxx** [JonathonLuiten/diff-gaussian-rasterization-w-depth#3]

**Comment by JonathonLuiten** [comment]
Yes this is simply for visualization. 15 is a good number for these “in the dome” scenes as any actual scene element is going to be closer than 15. 

Mostly this number actually affects how the camera moves as you move your mouse around in the 3D visualization when you zoom far out of the scene. By trial and error by trial and error I found a value of 15 gives natural seeming motions.

**Comment by gwxxx** [comment]
Thanks!
